/**
 * @fileoverview gRPC-Web generated client stub for crdt
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: crdt.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as crdt_pb from './crdt_pb'; // proto import: "crdt.proto"


export class CRDTServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendOperation = new grpcWeb.MethodDescriptor(
    '/crdt.CRDTService/SendOperation',
    grpcWeb.MethodType.UNARY,
    crdt_pb.Operation,
    crdt_pb.Empty,
    (request: crdt_pb.Operation) => {
      return request.serializeBinary();
    },
    crdt_pb.Empty.deserializeBinary
  );

  sendOperation(
    request: crdt_pb.Operation,
    metadata?: grpcWeb.Metadata | null): Promise<crdt_pb.Empty>;

  sendOperation(
    request: crdt_pb.Operation,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: crdt_pb.Empty) => void): grpcWeb.ClientReadableStream<crdt_pb.Empty>;

  sendOperation(
    request: crdt_pb.Operation,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: crdt_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/crdt.CRDTService/SendOperation',
        request,
        metadata || {},
        this.methodDescriptorSendOperation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/crdt.CRDTService/SendOperation',
    request,
    metadata || {},
    this.methodDescriptorSendOperation);
  }

  methodDescriptorSync = new grpcWeb.MethodDescriptor(
    '/crdt.CRDTService/Sync',
    grpcWeb.MethodType.SERVER_STREAMING,
    crdt_pb.Empty,
    crdt_pb.Operation,
    (request: crdt_pb.Empty) => {
      return request.serializeBinary();
    },
    crdt_pb.Operation.deserializeBinary
  );

  sync(
    request: crdt_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<crdt_pb.Operation> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/crdt.CRDTService/Sync',
      request,
      metadata || {},
      this.methodDescriptorSync);
  }

}

