// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: crdt.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CRDTService_SendOperation_FullMethodName = "/crdt.CRDTService/SendOperation"
	CRDTService_Sync_FullMethodName          = "/crdt.CRDTService/Sync"
)

// CRDTServiceClient is the client API for CRDTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CRDTServiceClient interface {
	// client sends operation
	SendOperation(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*Empty, error)
	// client subs to updates
	Sync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Operation], error)
}

type cRDTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCRDTServiceClient(cc grpc.ClientConnInterface) CRDTServiceClient {
	return &cRDTServiceClient{cc}
}

func (c *cRDTServiceClient) SendOperation(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CRDTService_SendOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRDTServiceClient) Sync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Operation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CRDTService_ServiceDesc.Streams[0], CRDTService_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Operation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CRDTService_SyncClient = grpc.ServerStreamingClient[Operation]

// CRDTServiceServer is the server API for CRDTService service.
// All implementations must embed UnimplementedCRDTServiceServer
// for forward compatibility.
type CRDTServiceServer interface {
	// client sends operation
	SendOperation(context.Context, *Operation) (*Empty, error)
	// client subs to updates
	Sync(*Empty, grpc.ServerStreamingServer[Operation]) error
	mustEmbedUnimplementedCRDTServiceServer()
}

// UnimplementedCRDTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCRDTServiceServer struct{}

func (UnimplementedCRDTServiceServer) SendOperation(context.Context, *Operation) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendOperation not implemented")
}
func (UnimplementedCRDTServiceServer) Sync(*Empty, grpc.ServerStreamingServer[Operation]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedCRDTServiceServer) mustEmbedUnimplementedCRDTServiceServer() {}
func (UnimplementedCRDTServiceServer) testEmbeddedByValue()                     {}

// UnsafeCRDTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRDTServiceServer will
// result in compilation errors.
type UnsafeCRDTServiceServer interface {
	mustEmbedUnimplementedCRDTServiceServer()
}

func RegisterCRDTServiceServer(s grpc.ServiceRegistrar, srv CRDTServiceServer) {
	// If the following call panics, it indicates UnimplementedCRDTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CRDTService_ServiceDesc, srv)
}

func _CRDTService_SendOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRDTServiceServer).SendOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRDTService_SendOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRDTServiceServer).SendOperation(ctx, req.(*Operation))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRDTService_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CRDTServiceServer).Sync(m, &grpc.GenericServerStream[Empty, Operation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CRDTService_SyncServer = grpc.ServerStreamingServer[Operation]

// CRDTService_ServiceDesc is the grpc.ServiceDesc for CRDTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRDTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crdt.CRDTService",
	HandlerType: (*CRDTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOperation",
			Handler:    _CRDTService_SendOperation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _CRDTService_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crdt.proto",
}
