// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: crdt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "add" or "remove" or "heartbeat"
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_crdt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Operation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_crdt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_crdt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_crdt_proto_rawDescGZIP(), []int{1}
}

var File_crdt_proto protoreflect.FileDescriptor

const file_crdt_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"crdt.proto\x12\x04crdt\"5\n" +
	"\tOperation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\a\n" +
	"\x05Empty2d\n" +
	"\vCRDTService\x12-\n" +
	"\rSendOperation\x12\x0f.crdt.Operation\x1a\v.crdt.Empty\x12&\n" +
	"\x04Sync\x12\v.crdt.Empty\x1a\x0f.crdt.Operation0\x01B\x11Z\x0fcolabcode/protob\x06proto3"

var (
	file_crdt_proto_rawDescOnce sync.Once
	file_crdt_proto_rawDescData []byte
)

func file_crdt_proto_rawDescGZIP() []byte {
	file_crdt_proto_rawDescOnce.Do(func() {
		file_crdt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crdt_proto_rawDesc), len(file_crdt_proto_rawDesc)))
	})
	return file_crdt_proto_rawDescData
}

var file_crdt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_crdt_proto_goTypes = []any{
	(*Operation)(nil), // 0: crdt.Operation
	(*Empty)(nil),     // 1: crdt.Empty
}
var file_crdt_proto_depIdxs = []int32{
	0, // 0: crdt.CRDTService.SendOperation:input_type -> crdt.Operation
	1, // 1: crdt.CRDTService.Sync:input_type -> crdt.Empty
	1, // 2: crdt.CRDTService.SendOperation:output_type -> crdt.Empty
	0, // 3: crdt.CRDTService.Sync:output_type -> crdt.Operation
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crdt_proto_init() }
func file_crdt_proto_init() {
	if File_crdt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crdt_proto_rawDesc), len(file_crdt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crdt_proto_goTypes,
		DependencyIndexes: file_crdt_proto_depIdxs,
		MessageInfos:      file_crdt_proto_msgTypes,
	}.Build()
	File_crdt_proto = out.File
	file_crdt_proto_goTypes = nil
	file_crdt_proto_depIdxs = nil
}
